Repository DSM-SUBMIT/rms_user_client, pull requests merged in 2021-11, with the labels that each got.

#66 64 Student ID Modal UI
  rms_user/src/components/modal/number/ModifyNumber.tsx
  rms_user/src/components/modal/number/style/index.ts
Labels: enhancement

#67 55 Deployment settings
  rms_user/netlify.toml
Labels: documentation

#68 39 Project Modal Redux & API 통신
  rms_user/src/components/main/style/index.ts
  rms_user/src/components/modal/Modal.tsx
  rms_user/src/components/modal/create/ProjectCreate.tsx
  rms_user/src/components/modal/create/style/index.ts
  rms_user/src/components/modal/delete/style/index.ts
  rms_user/src/components/modal/modify/Modify.tsx
  rms_user/src/components/modal/modify/style/index.ts
  rms_user/src/components/modal/number/style/index.ts
  rms_user/src/components/modal/otherModify/style/index.ts
  rms_user/src/components/modal/projectModify/style/index.ts
  rms_user/src/components/modal/view/myProjectView/myProjectView.tsx
  rms_user/src/components/modal/view/myProjectView/style/index.ts
  rms_user/src/components/modal/view/projectView/ProjectView.tsx
  rms_user/src/components/modal/view/projectView/style/index.ts
  rms_user/src/components/mypage/MyPage.tsx
  rms_user/src/components/writeReport/WriteReport.tsx
  rms_user/src/constance/viewProject/index.ts
  rms_user/src/modules/redux/reducer/project/index.ts
  rms_user/src/modules/redux/reducer/projectModify/index.ts
  rms_user/src/modules/redux/reducer/viewMyProject/index.ts
  rms_user/src/modules/redux/reducer/viewMyProject/interface/index.ts
Labels: enhancement

#70 69 Fix Errors
  rms_user/src/components/modal/modify/style/index.ts
  rms_user/src/components/modal/view/myProjectView/myProjectView.tsx
  rms_user/src/components/modal/view/myProjectView/style/index.ts
  rms_user/src/components/modal/view/projectView/style/index.ts
  rms_user/src/util/api/default/index.ts
Labels: enhancement

#72 33 Write Report Page Redux & api
  rms_user/src/components/writeReport/EditorItem.tsx
  rms_user/src/components/writeReport/WriteReport.tsx
  rms_user/src/containers/writeReport/WriteReportContainer.tsx
Labels: enhancement

#73 Hotfix
  rms_user/src/components/detailReport/ReportFirstPage.tsx
  rms_user/src/components/main/Main.tsx
  rms_user/src/components/modal/view/myProjectView/myProjectView.tsx
  rms_user/src/components/modal/view/projectView/ProjectView.tsx
  rms_user/src/components/writeReport/EditorItem.tsx
  rms_user/src/components/writeReport/WriteReport.tsx
  rms_user/src/constance/writeReport/index.ts
  rms_user/src/containers/writePlan/WritePlanContainer.tsx
  rms_user/src/containers/writeReport/WriteReportContainer.tsx
  rms_user/src/modules/redux/action/writeReport/index.ts
  rms_user/src/modules/redux/middleware/writeReport/index.ts
  rms_user/src/modules/redux/reducer/writeReport/index.ts
  rms_user/src/modules/redux/reducer/writeReport/interface/index.ts
  rms_user/src/util/api/writeReport/index.ts
  rms_user/src/util/hooks/writeReport/useWriteReport.tsx
Labels: bug

#75 74 Fix style
  rms_user/src/components/modal/create/style/index.ts
Labels: enhancement

#76 ⚡️ :: 리프레쉬 토큰
  rms_user/src/components/header/Header.tsx
Labels: enhancement

#77 74 Fix style
  rms_user/src/components/modal/view/myProjectView/myProjectView.tsx
  rms_user/src/components/writeReport/WriteReport.tsx
  rms_user/src/components/writeReport/style/index.ts
Labels: enhancement

#78 여러가지 오류 수정
  rms_user/src/components/detailReport/DetailReport.tsx
  rms_user/src/components/detailReport/style/index.ts
  rms_user/src/components/info/style/index.ts
  rms_user/src/components/main/ChooseField.tsx
  rms_user/src/components/modal/Modal.tsx
  rms_user/src/components/modal/create/ProjectCreate.tsx
  rms_user/src/components/modal/delete/DeleteBox.tsx
  rms_user/src/components/modal/delete/style/index.ts
  rms_user/src/components/modal/field/FieldBox.tsx
  rms_user/src/components/modal/modify/Modify.tsx
  rms_user/src/components/modal/modify/style/index.ts
  rms_user/src/components/modal/number/ModifyNumber.tsx
  rms_user/src/components/modal/otherModify/OtherModify.tsx
  rms_user/src/components/modal/projectModify/ProjectModify.tsx
  rms_user/src/components/modal/projectModify/style/index.ts
  rms_user/src/components/modal/team/ProjectTeam.tsx
  rms_user/src/components/modal/team/style/index.ts
  rms_user/src/components/modal/view/myProjectView/myProjectView.tsx
  rms_user/src/components/modal/view/myProjectView/style/index.ts
  rms_user/src/components/mypage/MyPage.tsx
  rms_user/src/components/mypage/style/index.ts
  rms_user/src/components/writePlan/WritePlan.tsx
  rms_user/src/components/writeReport/EditorItem.tsx
  rms_user/src/components/writeReport/WriteReport.tsx
  rms_user/src/containers/writePlan/WritePlanContainer.tsx
  rms_user/src/modules/redux/middleware/mypage/index.ts
  rms_user/src/modules/redux/middleware/userList/index.ts
  rms_user/src/modules/redux/middleware/viewMyProject/index.ts
  rms_user/src/modules/redux/middleware/viewProject/index.ts
  rms_user/src/modules/redux/reducer/projectDelete/index.ts
  rms_user/src/modules/redux/reducer/viewMyProject/index.ts
  rms_user/src/util/api/project/index.ts
  rms_user/src/util/api/writeReport/index.ts
  rms_user/src/util/hooks/viewMyProject/useViewMyProject.tsx
  rms_user/src/util/hooks/viewProject/useViewProject.tsx
Labels: bug

#79 Markdown 적용
  rms_user/package-lock.json
  rms_user/package.json
  rms_user/src/components/detailReport/WritedReport.tsx
  rms_user/src/components/detailReport/markdown/MarkdownRender.tsx
  rms_user/src/components/detailReport/markdown/katexWhitelist.ts
  rms_user/src/components/detailReport/style/index.ts
  rms_user/src/util/api/login/index.ts
  rms_user/yarn.lock
Labels: enhancement

#80 센터 오류 수정
  rms_user/src/components/modal/create/ProjectCreate.tsx
  rms_user/src/components/modal/view/myProjectView/myProjectView.tsx
  rms_user/src/components/modal/view/myProjectView/style/index.ts
  rms_user/src/components/modal/view/projectView/ProjectView.tsx
  rms_user/src/components/modal/view/projectView/style/index.ts
Labels: enhancement

#81 화면 오류 수정
  rms_user/src/components/modal/delete/DeleteBox.tsx
  rms_user/src/components/modal/field/style/index.ts
  rms_user/src/components/modal/modify/Modify.tsx
  rms_user/src/components/modal/modify/style/index.ts
  rms_user/src/components/modal/otherModify/OtherModify.tsx
  rms_user/src/components/modal/projectModify/ProjectModify.tsx
  rms_user/src/components/modal/projectModify/style/index.ts
  rms_user/src/components/modal/view/myProjectView/myProjectView.tsx
  rms_user/src/components/modal/view/myProjectView/style/index.ts
  rms_user/src/components/modal/view/projectView/ProjectView.tsx
  rms_user/src/components/modal/view/projectView/style/index.ts
Labels: enhancement

#82 :bug: :: 화면 비율 수정 뚝딱
  rms_user/src/components/modal/delete/style/index.ts
  rms_user/src/components/modal/view/myProjectView/myProjectView.tsx
  rms_user/src/components/modal/view/myProjectView/style/index.ts
Labels: enhancement
